/**
 * Every editor command: its name, where it sits in the menus ("Format/Text" is Format › Text), and
 * the parse state that marks its toolbar button as pressed. Command search follows this order.
 */
export const commandRegistry = {
  undo: { label: 'Undo', menu: 'Edit' }, redo: { label: 'Redo', menu: 'Edit' },
  cut: { label: 'Cut', menu: 'Edit' }, copy: { label: 'Copy', menu: 'Edit' },
  paste: { label: 'Paste', menu: 'Edit' }, selectAll: { label: 'Select all', menu: 'Edit' },
  deleteSelection: { label: 'Delete selection', menu: 'Edit' },
  duplicateLines: { label: 'Duplicate line/selection', menu: 'Edit/Lines' },
  moveLinesUp: { label: 'Move lines up', menu: 'Edit/Lines' },
  moveLinesDown: { label: 'Move lines down', menu: 'Edit/Lines' },
  deleteLines: { label: 'Delete lines', menu: 'Edit/Lines' },
  addLink: { label: 'Insert link', menu: 'Insert' },
  addImage: { label: 'Insert image', menu: 'Insert/Image' },
  addTable: { label: 'Insert table', menu: 'Insert' },
  hr: { label: 'Horizontal rule', menu: 'Insert', state: 'thematicBreak' },
  codeBlock: { label: 'Code block', menu: 'Insert/Elements', state: 'codeBlock' },
  bold: { label: 'Bold', menu: 'Format/Text', state: 'strong' },
  italic: { label: 'Italic', menu: 'Format/Text', state: 'emph' },
  strike: { label: 'Strikethrough', menu: 'Format/Text', state: 'strike' },
  code: { label: 'Inline code', menu: 'Format/Text', state: 'code' },
  ins: { label: 'Underline', menu: 'Format/Text' }, sup: { label: 'Superscript', menu: 'Format/Text' },
  sub: { label: 'Subscript', menu: 'Format/Text' }, mark: { label: 'Highlight', menu: 'Format/Text' },
  heading: { label: 'Heading', menu: 'Format/Paragraph styles', state: 'heading' },
  bulletList: { label: 'Bulleted list', menu: 'Format/Lists', state: 'bulletList' },
  orderedList: { label: 'Numbered list', menu: 'Format/Lists', state: 'orderedList' },
  taskList: { label: 'Task list', menu: 'Format/Lists', state: 'taskList' },
  alignLeft: { label: 'Align left', menu: 'Format/Align and indent' },
  alignCenter: { label: 'Centre', menu: 'Format/Align and indent' },
  alignRight: { label: 'Align right', menu: 'Format/Align and indent' },
  alignJustify: { label: 'Justify', menu: 'Format/Align and indent' },
  indent: { label: 'Indent', menu: 'Format/Align and indent' },
  outdent: { label: 'Outdent', menu: 'Format/Align and indent' },
  blockQuote: { label: 'Blockquote', menu: 'Format', state: 'blockQuote' },
  convertToComment: { label: 'Convert selection to comment', menu: 'Format' },
  convertToText: { label: 'Convert comment to ordinary text', menu: 'Format' },
  clearFormatting: { label: 'Clear text formatting', menu: 'Format' },
  addRowToUp: { label: 'Insert row above', menu: 'Format/Table', writeOnly: true },
  addRowToDown: { label: 'Insert row below', menu: 'Format/Table', writeOnly: true },
  removeRow: { label: 'Remove row', menu: 'Format/Table', writeOnly: true },
  addColumnToLeft: { label: 'Insert column left', menu: 'Format/Table', writeOnly: true },
  addColumnToRight: { label: 'Insert column right', menu: 'Format/Table', writeOnly: true },
  removeColumn: { label: 'Remove column', menu: 'Format/Table', writeOnly: true },
  alignColumn: { label: 'Align column', menu: 'Format/Table', writeOnly: true },
  removeTable: { label: 'Remove table', menu: 'Format/Table', writeOnly: true },
} as const;
export type CommandId = keyof typeof commandRegistry;
