import { describe,it,expect } from 'vitest';
import { attributionText,type Attribution } from '@/attributions';
import { fileStatistics,emailURL,mailtoLaunchLimit } from '../../src/ui/tools-dialogs';
import { fileTypeForName } from '../../src/documents/file-types';
const supplied:Attribution={project:'A [work] *title*',author:'Team',authorKind:'entity',given:'',family:'',url:'https://example.com/source',licence:'MIT',copyright:'2026 Supplied Owner',modifications:'Adapted table'};
describe('supplied attribution formats and exact utility snapshots',()=>{
 it('escapes Markdown metadata and retains supplied credit/source/licence/modifications',()=>{expect(attributionText(supplied,'markdown','markdown')).toBe('Credit: A \\[work\\] \\*title\\* by Team\nSource: <https://example.com/source>\nLicence: MIT\nModifications: Adapted table\n');});
 it('uses appropriate comments and SPDX tags without selecting a licence',()=>{expect(attributionText(supplied,'comment','typescript')).toContain('/*\nCredit:');expect(attributionText(supplied,'comment','markdown')).toContain('<!--\nCredit:');expect(attributionText(supplied,'spdx','yaml')).toBe('# SPDX-FileCopyrightText: 2026 Supplied Owner\n# SPDX-License-Identifier: MIT\n');expect(()=>attributionText(supplied,'comment','json')).toThrow('does not support');expect(()=>attributionText({...supplied,licence:''},'spdx','css')).toThrow('Supply copyright');});
 it('rejects escaping a comment, multiline metadata and unsafe URL output',()=>{for(const project of ['title */ injected','title\nline'])expect(()=>attributionText({...supplied,project},'comment','css')).toThrow();expect(()=>attributionText({...supplied,author:'bad -->'},'comment','html')).toThrow();expect(()=>attributionText({...supplied,url:'javascript:alert(1)'},'markdown','markdown')).toThrow('HTTP');});
 it('quotes CFF YAML scalars, requires explicit person/entity fields and keeps freeform licence as a comment',()=>{const output=attributionText({...supplied,project:'Quoted "title": work'},'cff','markdown');expect(output).toContain('cff-version: 1.2.0\nmessage:');expect(output).toContain('title: "Quoted \\"title\\": work"');expect(output).toContain('  - name: "Team"');expect(output).toContain('# Supplied licence information: "MIT"');expect(output).not.toContain('\nlicense:');expect(attributionText({...supplied,authorKind:'person',family:'Doe',given:'Jane'},'cff','markdown')).toContain('  - family-names: "Doe"\n    given-names: "Jane"');expect(()=>attributionText({...supplied,authorKind:'person'},'cff','markdown')).toThrow('family name');expect(fileTypeForName('CITATION.cff')).toBe('yaml');});
 it('counts raw BOM/newlines/Unicode bytes and preserves the complete email body',()=>{const source='\ufeffone 😀\r\ntwo\n';expect(fileStatistics(source)).toEqual({words:3,characters:12,lines:3,bytes:17});expect(fileStatistics('')).toEqual({words:0,characters:0,lines:0,bytes:0});const url=emailURL('title & source',source);expect(new URL(url).searchParams.get('body')).toBe(source);expect(new URL(url).searchParams.get('subject')).toBe('title & source');expect(emailURL('title','x'.repeat(2000)).length).toBeGreaterThan(mailtoLaunchLimit);});
});
